import type { Metadata } from "next";
import { Changa } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/navbar";

const changa = Changa({
  subsets: ['arabic'],   // choose subsets (latin, arabic, etc.)
  weight: '400',      // optional: improves rendering
})


export const metadata: Metadata = {
  title: "منصة تعليم القرآن الكريم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${changa.className} antialiased bg-amber-100 text-green-900`}
      >
        <Navbar />
        <div className="md:p-8 p-4">
          {children}
        </div>

      </body>
    </html>
  );
}
