import type { Metadata } from "next";
import { Changa } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/navbar";

const changa = Changa({
  subsets: ['arabic'],   // choose subsets (latin, arabic, etc.)
  weight: '400',      // optional: improves rendering
})


export const metadata: Metadata = {
  title: "منصة تعليم القرآن الكريم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${changa.className} antialiased  md:bg-gradient-to-l md:from-amber-50 md:to-amber-300 bg-gradient-to-b from-amber-50 to-amber-300 text-green-900 text-end`}
      >
        <Navbar />
        <div className="md:p-8 p-4">
          {children}
        </div>

      </body>
    </html>
  );
}
